### ISSUE TITLE
Update protos in google/cloud/audit

### ISSUE THREAD

**Issue by parthea** [googleapis/python-audit-log#122]
The protos in https://github.com/googleapis/python-audit-log/tree/main/google/cloud/audit are out of date. They should be updating automatically using [owlbot.py](https://github.com/googleapis/python-audit-log/blob/main/owlbot.py) but the automation is not working as expected.

For example,
see https://github.com/googleapis/python-audit-log/blob/main/google/cloud/audit/audit_log.proto which hasn't been updated in 4 years whereas https://github.com/googleapis/googleapis/blob/master/google/cloud/audit/audit_log.proto has been updated in the last 2 years.

**Comment by cglewis** [comment]
Can the fix for this be prioritized? We're running into issues trying to use the google-cloud-logging library (which depends on this library) and can't use them because this file is out of date:
```
  File "/install/.venv/lib/python3.11/site-packages/google/cloud/logging_v2/entries.py", line 31, in <module>
    import google.cloud.audit.audit_log_pb2  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/install/.venv/lib/python3.11/site-packages/google/cloud/audit/audit_log_pb2.py", line 62, in <module>
    _descriptor.FieldDescriptor(
  File "/install/.venv/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
```
